[workspace]
resolver = '2'
members = ["crates/app-egui", "crates/app-gpui", "crates/models"]
default-members = ["crates/app-egui"]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
