use std::path::PathBuf;

use crate::app;
use tracing::{error, info};

// include migration script generated by build.rs
include!(concat!(env!("OUT_DIR"), "/migrations.rs"));

pub fn get_db_path() -> Result<PathBuf, String> {
    let dir = app::get_app_data_dir()?;
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    return Ok(dir.join("nativedoctor.db"));
}

/// Ensures the DB schema is up to date by running any migrations that haven't been applied yet.
/// Migrations are SQL files from `migrations/`, embedded at compile time and applied in filename order.
pub fn init_db(conn: &mut rusqlite::Connection) -> Result<(), String> {
    // Table that records which migrations we've already run (name = filename, applied_at = unix time).
    conn.execute(
        "CREATE TABLE IF NOT EXISTS _migrations (name TEXT PRIMARY KEY, applied_at INTEGER NOT NULL)",
        [],
    )
    .map_err(|e| {
        let msg = e.to_string();
        error!(error = %msg, "Failed to create _migrations table");
        msg
    })?;

    // get all the migration name we already ran
    let mut applied: Vec<String> = conn
        .prepare("SELECT name FROM _migrations")
        .map_err(|e| {
            let msg = e.to_string();
            error!(error = %msg, "Failed to prepare migrations query");
            msg
        })?
        .query_map([], |row| row.get(0))
        .map_err(|e| {
            let msg = e.to_string();
            error!(error = %msg, "Failed to iterate migrations query rows");
            msg
        })?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| {
            let msg = e.to_string();
            error!(error = %msg, "Failed to collect applied migrations");
            msg
        })?;

    info!(
        applied_migrations = applied.len(),
        total_migrations = MIGRATIONS.len(),
        "Initializing DB migrations"
    );

    // Run each migration that isn't in _migrations yet, in one transaction so we roll back on failure.
    let tx = conn.transaction().map_err(|e| {
        let msg = e.to_string();
        error!(error = %msg, "Failed to start migrations transaction");
        msg
    })?;
    for (name, sql) in MIGRATIONS {
        if applied.contains(&name.to_string()) {
            continue;
        }

        info!(migration = name, "Applying migration");
        tx.execute_batch(sql).map_err(|e| {
            let msg = e.to_string();
            error!(migration = name, error = %msg, "Migration failed");
            msg
        })?;

        let ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_err(|e| {
                let msg = e.to_string();
                error!(migration = name, error = %msg, "Failed to compute unix timestamp");
                msg
            })?
            .as_secs() as i64;

        tx.execute(
            "INSERT INTO _migrations (name, applied_at) VALUES (?1, ?2)",
            rusqlite::params![name, ts],
        )
        .map_err(|e| {
            let msg = e.to_string();
            error!(migration = name, error = %msg, "Failed to record applied migration");
            msg
        })?;
        applied.push(name.to_string());

        info!(migration = name, "Migration applied");
    }

    tx.commit().map_err(|e| {
        let msg = e.to_string();
        error!(error = %msg, "Failed to commit migrations transaction");
        msg
    })?;
    return Ok(());
}
