[package]
name = "nd-app"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit"] }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component" }
anyhow = "1.0"
tracing-subscriber = {version="0.3.23", features=["env-filter"]}
tracing = "0.1"
serde = "1.0.228"
